import { Batch, Recipe, ScobyRecord } from '@/types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-classic-black',
    name: 'Tradičná Čierna Kombucha',
    category: 'CLASSIC',
    description: 'Klasická plná chuť s výraznými čajovými a jemne kyselkavými tónmi. Ideálna pre začiatočníkov.',
    teaType: 'BLACK',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Vyvážená, kyselkavo-sladká, jemne jablková a čajová',
    instructions: [
      'Uvarte 1L vody a lúhujte čierny čaj 10 minút.',
      'Vmiešajte cukor, kým sa plne nerozpustí.',
      'Dolejte zvyšnú studenú pitnú vodu na ochladenie (pod 28 °C).',
      'Pridajte štartovaciu tekutinu a vložte zdravý SCOBY.',
      'Zakryte priedušnou tkaninou a zaistite gumičkou. Nechajte fermentovať na tmavom mieste pri 22–26 °C.',
    ],
    notes: 'Tradičný čierny čaj vyživuje SCOBY najlepšie.',
    recommendedSecondFermentAdditions: ['Čerstvý zázvor', 'Citrónová šťava', 'Jablkové pyré'],
  },
  {
    id: 'rec-green-jasmine',
    name: 'Svieža Zelená Kombucha',
    category: 'CLASSIC',
    description: 'Ľahký, svieži a jemne travnatý nápoj s vyšším obsahom antioxidantov.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6.5,
    sugarGramPerLiter: 65,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 7,
    flavorProfile: 'Ľahká, svieža, travnatá s citrusovým podtónom',
    instructions: [
      'Zalejte zelený čaj vodou s teplotou max. 80 °C a lúhujte 7 minút.',
      'Rozpustite cukor a dolejte studenú vodu.',
      'Pred pridaním SCOBY sa uistite, že čaj nie je horúci.',
    ],
    notes: 'Zelený čaj fermentuje o 1-2 dni rýchlejšie ako čierny.',
    recommendedSecondFermentAdditions: ['Limetka', 'Mäta', 'Uhorka', 'Baza'],
  },
  {
    id: 'rec-moon-mix',
    name: 'Mesačný Mix (Čierny + Zelený čaj)',
    category: 'CLASSIC',
    description: 'Dokonalá rovnováha medzi plnosťou čierneho čaju a sviežosťou zeleného čaju.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Komplexná, jemne ovocná, vyvážená',
    instructions: [
      'Lúhujte 50% čierneho čaju (10 min) a 50% zeleného čaju (7 min).',
      'Pridajte cukor a studenú vodu.',
    ],
    notes: 'Najvyhľadávanejšia receptúra pre všestranné ochucovanie v 2F.',
    recommendedSecondFermentAdditions: ['Lesné ovocie', 'Jahody', 'Ibištek'],
  },
];

export const INITIAL_SCOBIES: ScobyRecord[] = [
  {
    id: 'scoby-1',
    userId: 'u1',
    name: 'Materský SCOBY (Tradičný čaj)',
    generation: 3,
    healthStatus: 'HEALTHY',
    notes: 'Hrúbka cca 1.5 cm, rovnomerná svetlá farba, zdravá a vysoko aktívna kultúra.',
    hotelStartDate: '2026-08-15T10:00:00Z',
    lastUsedDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'kb-active-1',
    userId: 'u1',
    codeNumber: 'KB-001',
    name: 'Domáca Kombucha #1 – Čierny čaj (3.5L)',
    recipeId: 'rec-classic-black',
    recipeName: 'Tradičná Čierna Kombucha',
    teaType: 'BLACK',
    volumeLiters: 3.5,
    teaGram: 24.5,
    sugarGram: 245,
    starterLiquidMl: 350,
    waterLiters: 3.15,
    scobyId: 'scoby-1',
    scobyName: 'Materský SCOBY (Tradičný čaj)',
    startDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(), // 5 dní dozadu
    targetTasteDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(), // o 2 dni (7. deň)
    targetBottleDate: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
    state: 'FIRST_FERMENTATION',
    notes: 'Založené v sklenenej 3.5L nádobe. Umiestnené v teplej komore mimo priameho slnka.',
    measurements: [
      {
        id: 'm1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        temperature: 24.0,
        ph: 4.2,
        sugarBrix: 7.0,
        sugarGramPerLiter: 70,
        sweetnessRating: 5,
        acidityRating: 1,
        fizzRating: 1,
        measuredBy: 'USER',
        notes: 'Počiatočný stav po zmiešaní sladkého čaju a štartéra. Silná sladkosť.',
      },
      {
        id: 'm2',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        temperature: 23.5,
        ph: 3.6,
        sugarBrix: 5.2,
        sugarGramPerLiter: 52,
        sweetnessRating: 4,
        acidityRating: 2,
        fizzRating: 1,
        measuredBy: 'USER',
        notes: 'Baktérie a kvasinky naplno pracujú, na hladine sa tvorí jemný film novej kultúry.',
      },
      {
        id: 'm3',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        temperature: 23.8,
        ph: 3.2,
        sugarBrix: 3.8,
        sugarGramPerLiter: 38,
        sweetnessRating: 3,
        acidityRating: 3,
        fizzRating: 2,
        measuredBy: 'USER',
        notes: 'Príjemná polosladká chuť s vyvíjajúcou sa kyselkavosťou, pripravená na finálnu degustáciu.',
      },
    ],
    history: [
      {
        id: 'h1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        newState: 'FIRST_FERMENTATION',
        title: 'Várka založená (1F)',
        description: 'Uvarený čierny čaj, rozpustený trstinový cukor, pridaný štartér a materský SCOBY.',
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
];
