import { Batch, Recipe, ScobyRecord } from '@/types';

export const INITIAL_RECIPES: Recipe[] = [
  // 1. SCOBY HOTEL
  {
    id: 'rec-scoby-hotel-elixir',
    name: 'SCOBY Hotel – Výživný Elixír na Uchovanie',
    category: 'SCOBY_HOTEL',
    description: 'Špeciálny koncentrovanejší nálev na dlhodobé uchovanie a výživu záložných materských kultúr v hoteli.',
    teaType: 'BLACK',
    defaultVolumeLiters: 1.5,
    teaGramPerLiter: 8,
    sugarGramPerLiter: 80,
    starterMlPerLiter: 250, // vyšší podiel kyslého octu na ochranu
    waterLitersPerLiter: 0.75,
    estimatedDaysFirstFerment: 30,
    flavorProfile: 'Silne kyslý, octový, plný organických kyselín a ochranných látok',
    instructions: [
      'Uvarte silný nálev z kvalitného čierneho čaju (8g na 1L vody) a lúhujte 15 minút.',
      'Rozpustite 80g trstinového cukru na liter a nechajte úplne vychladnúť pod 25 °C.',
      'Zmiešajte s min. 250 ml silného vyzretého kombucha octu (pH < 3.0), aby bol hotel chránený pred plesňou.',
      'Vložte materské kultúry tak, aby boli ponorené. Zakryte plátnom a skladujte v tme.',
      'Prikrmujte čerstvým sladeným čajom každých 4 až 6 týždňov.',
    ],
    notes: 'Vysoká acidita (pH 2.6 - 3.0) vytvára nepreniknuteľnú bariéru proti plesniam a škodcom.',
    isFavorite: true,
  },

  // 2. JUN KOMBUCHA
  {
    id: 'rec-jun-honey',
    name: 'Jun Kombucha – Šampanské s Medom',
    category: 'EXPERIMENTAL',
    description: 'Vznešená sestra kombuchy pripravená zo zeleného čaju a surového včelieho medu. Rýchlejšia fermentácia a delikátna chuť.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6,
    sugarGramPerLiter: 60, // reprezentuje gramy pravého medu
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 5,
    flavorProfile: 'Jemná, kvetinová, jemne medová so šampanskou perlivosťou',
    instructions: [
      'Zelený čaj Sencha zalejte vodou s teplotou 75–80 °C a lúhujte 5 minút.',
      'Čaj sceďte a nechajte vychladnúť na izbovú teplotu (pod 35 °C, aby sa nezničili enzýmy v mede).',
      'Dôkladne vmiešajte kvalitný kvetový alebo lesný med.',
      'Pridajte štartér a Jun kultúru. Fermentujte pri 20–24 °C len 4–6 dní (kvasí rýchlejšie ako čierna kombucha).',
    ],
    notes: 'Med má prirodzené antibakteriálne vlastnosti – kultúra musí byť postupne adaptovaná na med.',
    isFavorite: true,
  },

  // 3. CLASSIC BLACK
  {
    id: 'rec-classic-black',
    name: 'Tradičná Čierna Kombucha (Ceylon / Assam)',
    category: 'CLASSIC',
    description: 'Klasická plná chuť s výraznými čajovými a jemne kyselkavými tónmi. Zlatý štandard pre začiatočníkov aj pokročilých.',
    teaType: 'BLACK',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Vyvážená, kyselkavo-sladká, jemne jablková a čajová',
    instructions: [
      'Uvarte 1L vody a lúhujte sypaný čierny čaj 10 minút.',
      'Vmiešajte trstinový cukor, kým sa plne nerozpustí.',
      'Dolejte zvyšnú studenú pitnú vodu na ochladenie (pod 26 °C).',
      'Pridajte štartovaciu tekutinu a vložte zdravý SCOBY.',
      'Zakryte priedušnou tkaninou a zaistite gumičkou. Nechajte fermentovať pri 22–26 °C.',
    ],
    notes: 'Tradičný čierny čaj vyživuje SCOBY najlepšie a zabezpečuje dlhú životnosť kultúry.',
    recommendedSecondFermentAdditions: ['Čerstvý zázvor', 'Citrónová šťava', 'Jablkový mušt'],
    isDefault: true,
    isFavorite: true,
  },

  // 4. GREEN JASMINE
  {
    id: 'rec-green-jasmine',
    name: 'Svieža Zelená Kombucha (Sencha / Jazmín)',
    category: 'CLASSIC',
    description: 'Ľahký, svieži a jemne trávnatý nápoj s vyšším obsahom antioxidantov a jemnejším telom.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6.5,
    sugarGramPerLiter: 65,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 7,
    flavorProfile: 'Ľahká, svieža, kvetinová s citrusovým podtónom',
    instructions: [
      'Zalejte zelený čaj vodou s teplotou max. 80 °C a lúhujte 7 minút.',
      'Rozpustite cukor a dolejte studenú vodu.',
      'Pred pridaním SCOBY skontrolujte, že teplota klesla pod 26 °C.',
    ],
    notes: 'Zelený čaj fermentuje o 1-2 dni rýchlejšie ako čierny.',
    recommendedSecondFermentAdditions: ['Limetka', 'Čerstvá mäta', 'Uhorka'],
  },

  // 5. MOON MIX
  {
    id: 'rec-moon-mix',
    name: 'Mesačný Mix (50% Čierny + 50% Zelený)',
    category: 'CLASSIC',
    description: 'Dokonalá rovnováha medzi plnosťou čierneho čaju a sviežosťou zeleného čaju. Najlepšia základňa pre ovocné 2F.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Komplexná, harmonická, jemne ovocná s čistým záverom',
    instructions: [
      'Lúhujte čierny čaj (10 min) a zelený čaj (7 min).',
      'Pridajte cukor a dolejte studenú vodu na výsledný objem.',
    ],
    notes: 'Ideálna kombinácia minerálov pre kvasinky a polyfenolov pre baktérie.',
    recommendedSecondFermentAdditions: ['Lesné ovocie', 'Jahody', 'Ibištek'],
    isFavorite: true,
  },

  // 6. 2F MALINOVKA: Šumivá Malinová Limonáda s Mätou
  {
    id: 'rec-2f-raspberry-lemonade',
    name: '2F Malinovka: Šumivá Malina & Mäta',
    category: 'SODA_LEMONADE',
    description: 'Najpopulárnejšia domáca kombucha malinovka! Bohatá ružová pena, prírodné bublinky a osviežujúca chuť zrelých malín.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.0,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Intenzívne malinová, šumivá, svieža mentolová dochuť',
    instructions: [
      'Do každej 500ml patentovej fľaše vložte 25g jemne popučených malín.',
      'Pridajte 3-4 lístky čerstvej mäty a pol lyžičky trstinového cukru na naštartovanie perlenia.',
      'Zalejte hotovou 1F kombuchou, nechajte 2.5 cm voľného priestoru pod hrdlom.',
      'Dôkladne uzavrite a fermentujte pri izbovej teplote 2–3 dni.',
      'Pred otvorením dajte na 12 hodín do chladničky (aby sa CO₂ rozpustil a nepenil nekontrolovane).',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 25,
      sugarGrams: 3,
      herbsNotes: '3–4 lístky čerstvej mäty',
      fermentDaysMin: 2,
      fermentDaysMax: 3,
      fizzLevel: 'Silné šumivé (šampanské)',
    },
    isFavorite: true,
  },

  // 7. 2F KLASIK: Zázvor & Citrónový Tonik
  {
    id: 'rec-2f-ginger-lemon',
    name: '2F Klasik: Zázvorovo-Citrónový Tonik',
    category: 'SECOND_FERMENTATION',
    description: 'Absolútny svetový favorit. Pikantný čerstvý zázvor s citrusovou kyselkavosťou a silným prírodným perlením na podporu imunity.',
    teaType: 'BLACK',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Pikantná zázvorová hrejivosť, svieži citrón, bohaté perlenie',
    instructions: [
      'Nastrúhajte 10–12g čerstvého neošúpaného zázvoru na 500ml fľašu.',
      'Vytlačte 15ml čerstvej citrónovej šťavy.',
      'Zalejte mladou kombuchou, fľašu uzavrite a nechajte fermentovať 2–4 dni.',
      'Zázvor obsahuje prírodné kvasinky, ktoré vytvárajú výnimočne bohaté bublinky.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 12,
      juiceMl: 15,
      sugarGrams: 2,
      herbsNotes: 'Čerstvo nastrúhaný zázvor',
      fermentDaysMin: 2,
      fermentDaysMax: 4,
      fizzLevel: 'Silné šumivé (šampanské)',
    },
    isFavorite: true,
  },

  // 8. 2F SODA: Lesné Plody & Ibištekový Rubín
  {
    id: 'rec-2f-wild-berry-hibiscus',
    name: '2F Malinovka: Lesné Plody & Ibištek',
    category: 'SODA_LEMONADE',
    description: 'Krásna hlboká rubínová farba s tónmi černíc, čučoriedok a kvetinového ibišteka. Prírodná zdravá alternatíva k ovocným limonádam.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Plná ovocná chuť lesného ovocia, trpkasto-sladká s rubínovou farbou',
    instructions: [
      'Do 500ml fľaše pridajte 20g zmesi čučoriedok a černíc.',
      'Pridajte 1 čajovú lyžičku sušených kvetov ibišteka sudánskeho (dáva žiarivú farbu a kyselinku).',
      'Dolejte kombuchu, uzatvorte a nechajte pracovať 2–3 dni.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 20,
      herbsNotes: '1 ČL sušeného ibišteka',
      fermentDaysMin: 2,
      fermentDaysMax: 3,
      fizzLevel: 'Stredné perlenie',
    },
    isFavorite: true,
  },

  // 9. 2F TROPICAL: Mango & Marakuja
  {
    id: 'rec-2f-tropical-mango',
    name: '2F Exotika: Tropické Mango & Marakuja',
    category: 'SECOND_FERMENTATION',
    description: 'Sladká chuť zrelého manga vyvážená iskrivou aciditou marakuje (passion fruit). Hodvábna pena a exotický zážitok.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6.5,
    sugarGramPerLiter: 65,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 7,
    flavorProfile: 'Hustá tropická aróma, exotická marakujová sviežosť',
    instructions: [
      'Použite 25g jemného mangového pyré alebo zrelých kociek manga na 500ml.',
      'Doplňte 10ml marakujovej 100% šťavy.',
      'Mango má vysoký obsah fruktózy, preto nie je potrebné pridávať žiadny ďalší cukor.',
      'Fermentujte 2–3 dni pri teplote 23–25 °C.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 25,
      juiceMl: 10,
      fermentDaysMin: 2,
      fermentDaysMax: 3,
      fizzLevel: 'Stredné perlenie',
    },
  },

  // 10. 2F SPICED APPLE: Jablkový Mušt & Škorica
  {
    id: 'rec-2f-spiced-apple',
    name: '2F Jesenná: Jablkový Mušt & Cejlónska Škorica',
    category: 'SECOND_FERMENTATION',
    description: 'Hrejivá kombinácia pripomínajúca remeselný jablčný cider. Ideálna na chladnejšie mesiace.',
    teaType: 'BLACK',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Jablkový koláčik, teplá škorica a perlivý jablčný cider',
    instructions: [
      'Nalejte 40ml 100% prírodného nefiltrovaného jablkového muštu do 500ml fľaše.',
      'Vložte polovičku celej tyčinky cejlónskej škorice a 1 klinček.',
      'Dolejte kombuchou a nechajte fermentovať 3–4 dni.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      juiceMl: 40,
      herbsNotes: '1/2 tyčinky škorice + 1 klinček',
      fermentDaysMin: 3,
      fermentDaysMax: 4,
      fizzLevel: 'Stredné perlenie',
    },
  },

  // 11. 2F BLUEBERRY LAVENDER
  {
    id: 'rec-2f-blueberry-lavender',
    name: '2F Relax: Čučoriedka & Kulinárska Levanduľa',
    category: 'SECOND_FERMENTATION',
    description: 'Elegantné a voňavé spojenie antioxidantov z lesných čučoriedok a jemných tónov levandule.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Jemne trpkastá, kvetinová, upokojujúca vôňa',
    instructions: [
      'Pridajte 20g popučených lesných čučoriedok a štipku (cca 10 sušených kvietkov) kulinárskej levandule.',
      'Fľašujte a nechajte pracovať 2–3 dni.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 20,
      herbsNotes: 'Štipka kulinárskej levandule',
      fermentDaysMin: 2,
      fermentDaysMax: 3,
      fizzLevel: 'Jemné perlenie',
    },
  },

  // 12. 2F STRAWBERRY BASIL
  {
    id: 'rec-2f-strawberry-basil',
    name: '2F Malinovka: Jahoda & Talianska Bazalka',
    category: 'SODA_LEMONADE',
    description: 'Neuveriteľne svieža kombinácia sladkých jahôd a voňavej bazalky. Letná limonáda s plným perlením.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6.5,
    sugarGramPerLiter: 65,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 7,
    flavorProfile: 'Jahodová sladkosť s bylinkovou bazalkovou hĺbkou',
    instructions: [
      'Do 500ml fľaše vložte 25g nakrájaných jahôd a 2 natrhané lístky čerstvej bazalky.',
      'Dolejte zelenú kombuchu a fermentujte 2 dni.',
    ],
    secondFermentRatio: {
      bottleVolumeMl: 500,
      fruitGrams: 25,
      herbsNotes: '2 natrhané lístky čerstvej bazalky',
      fermentDaysMin: 2,
      fermentDaysMax: 3,
      fizzLevel: 'Silné šumivé (šampanské)',
    },
  },
];

export const INITIAL_SCOBIES: ScobyRecord[] = [
  {
    id: 'scoby-1',
    userId: 'u1',
    name: 'Materský SCOBY (Tradičný čaj)',
    generation: 3,
    healthStatus: 'HEALTHY',
    notes: 'Hrúbka cca 1.5 cm, rovnomerná svetlá farba, zdravá a vysoko aktívna kultúra.',
    hotelStartDate: '2026-08-15T10:00:00Z',
    lastUsedDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'kb-active-1',
    userId: 'u1',
    codeNumber: 'KB-001',
    name: 'Domáca Kombucha #1 – Čierny čaj (3.5L)',
    recipeId: 'rec-classic-black',
    recipeName: 'Tradičná Čierna Kombucha',
    teaType: 'BLACK',
    volumeLiters: 3.5,
    teaGram: 24.5,
    sugarGram: 245,
    starterLiquidMl: 350,
    waterLiters: 3.15,
    scobyId: 'scoby-1',
    scobyName: 'Materský SCOBY (Tradičný čaj)',
    startDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(), // 5 dní dozadu
    targetTasteDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(), // o 2 dni (7. deň)
    targetBottleDate: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
    state: 'FIRST_FERMENTATION',
    notes: 'Založené v sklenenej 3.5L nádobe. Umiestnené v teplej komore mimo priameho slnka.',
    measurements: [
      {
        id: 'm1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        temperature: 24.0,
        ph: 4.2,
        sugarBrix: 7.0,
        sugarGramPerLiter: 70,
        sweetnessRating: 5,
        acidityRating: 1,
        fizzRating: 1,
        measuredBy: 'USER',
        notes: 'Počiatočný stav po zmiešaní sladkého čaju a štartéra. Silná sladkosť.',
      },
      {
        id: 'm2',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        temperature: 23.5,
        ph: 3.6,
        sugarBrix: 5.2,
        sugarGramPerLiter: 52,
        sweetnessRating: 4,
        acidityRating: 2,
        fizzRating: 1,
        measuredBy: 'USER',
        notes: 'Baktérie a kvasinky naplno pracujú, na hladine sa tvorí jemný film novej kultúry.',
      },
      {
        id: 'm3',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        temperature: 23.8,
        ph: 3.2,
        sugarBrix: 3.8,
        sugarGramPerLiter: 38,
        sweetnessRating: 3,
        acidityRating: 3,
        fizzRating: 2,
        measuredBy: 'USER',
        notes: 'Príjemná polosladká chuť s vyvíjajúcou sa kyselkavosťou, pripravená na finálnu degustáciu.',
      },
    ],
    history: [
      {
        id: 'h1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        newState: 'FIRST_FERMENTATION',
        title: 'Várka založená (1F)',
        description: 'Uvarený čierny čaj, rozpustený trstinový cukor, pridaný štartér a materský SCOBY.',
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
];
