import { Batch, Recipe, ScobyRecord } from '@/types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-classic-black',
    name: 'Tradičná Čierna Kombucha',
    category: 'CLASSIC',
    description: 'Klasická plná chuť s výraznými čajovými a jemne kyselkavými tónmi. Ideálna pre začiatočníkov.',
    teaType: 'BLACK',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Vyvážená, kyselkavo-sladká, jemne jablková a čajová',
    instructions: [
      'Uvarte 1L vody a lúhujte čierny čaj 10 minút.',
      'Vmiešajte cukor, kým sa plne nerozpustí.',
      'Dolejte zvyšnú studenú pitnú vodu na ochladenie (pod 28 °C).',
      'Pridajte štartovaciu tekutinu a vložte zdravý SCOBY.',
      'Zakryte priedušnou tkaninou a zaistite gumičkou. Nechajte fermentovať na tmavom mieste pri 22–26 °C.',
    ],
    notes: 'Tradičný čierny čaj vyživuje SCOBY najlepšie.',
    recommendedSecondFermentAdditions: ['Čerstvý zázvor', 'Citrónová šťava', 'Jablkové pyré'],
  },
  {
    id: 'rec-green-jasmine',
    name: 'Svieža Zelená Kombucha',
    category: 'CLASSIC',
    description: 'Ľahký, svieži a jemne travnatý nápoj s vyšším obsahom antioxidantov.',
    teaType: 'GREEN',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 6.5,
    sugarGramPerLiter: 65,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 7,
    flavorProfile: 'Ľahká, svieža, travnatá s citrusovým podtónom',
    instructions: [
      'Zalejte zelený čaj vodou s teplotou max. 80 °C a lúhujte 7 minút.',
      'Rozpustite cukor a dolejte studenú vodu.',
      'Pred pridaním SCOBY sa uistite, že čaj nie je horúci.',
    ],
    notes: 'Zelený čaj fermentuje o 1-2 dni rýchlejšie ako čierny.',
    recommendedSecondFermentAdditions: ['Limetka', 'Mäta', 'Uhorka', 'Baza'],
  },
  {
    id: 'rec-moon-mix',
    name: 'Mesačný Mix (Čierny + Zelený čaj)',
    category: 'CLASSIC',
    description: 'Dokonalá rovnováha medzi plnosťou čierneho čaju a sviežosťou zeleného čaju.',
    teaType: 'BLACK_GREEN_MIX',
    defaultVolumeLiters: 3.5,
    teaGramPerLiter: 7,
    sugarGramPerLiter: 70,
    starterMlPerLiter: 100,
    waterLitersPerLiter: 0.9,
    estimatedDaysFirstFerment: 8,
    flavorProfile: 'Komplexná, jemne ovocná, vyvážená',
    instructions: [
      'Lúhujte 50% čierneho čaju (10 min) a 50% zeleného čaju (7 min).',
      'Pridajte cukor a studenú vodu.',
    ],
    notes: 'Najvyhľadávanejšia receptúra pre všestranné ochucovanie v 2F.',
    recommendedSecondFermentAdditions: ['Lesné ovocie', 'Jahody', 'Ibištek'],
  },
];

export const INITIAL_SCOBIES: ScobyRecord[] = [
  {
    id: 'scoby-1',
    userId: 'u1',
    name: 'Mama SCOBY (Ceylon)',
    generation: 4,
    healthStatus: 'HEALTHY',
    notes: 'Hrúbka cca 1.5 cm, krasne svetlá, veľmi aktívna.',
    hotelStartDate: '2026-08-01T10:00:00Z',
    lastUsedDate: '2026-09-05T10:00:00Z',
  },
  {
    id: 'scoby-2',
    userId: 'u1',
    name: 'Druhý SCOBY (Záloha v hoteli)',
    generation: 3,
    healthStatus: 'RESTING',
    notes: 'Uložený v silnom kombucha octe ako záloha.',
    hotelStartDate: '2026-07-15T10:00:00Z',
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'kb-active-1',
    userId: 'u1',
    codeNumber: 'KB-042',
    name: 'Jesenný Čierny Klasik (3.5L)',
    recipeId: 'rec-classic-black',
    recipeName: 'Tradičná Čierna Kombucha',
    teaType: 'BLACK',
    volumeLiters: 3.5,
    teaGram: 24.5,
    sugarGram: 245,
    starterLiquidMl: 350,
    waterLiters: 3.15,
    scobyId: 'scoby-1',
    scobyName: 'Mama SCOBY (Ceylon)',
    startDate: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(), // 6 days ago
    targetTasteDate: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(), // tomorrow
    targetBottleDate: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
    state: 'FIRST_FERMENTATION',
    notes: 'Teplota v špajzi je stabilná na 23°C.',
    measurements: [
      {
        id: 'm1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        temperature: 23.5,
        ph: 3.8,
        measuredBy: 'USER',
        notes: 'Začína sa tvoriť nová priehľadná blana na povrchu.',
      },
      {
        id: 'm2',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        temperature: 24.0,
        ph: 3.2,
        measuredBy: 'RASPBERRY_PI',
        notes: 'Automatické meranie z Pi senzora.',
      },
    ],
    history: [
      {
        id: 'h1',
        batchId: 'kb-active-1',
        timestamp: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
        newState: 'STARTED',
        title: 'Várka založená',
        description: 'Pripravená tekutina (3.5L), pridaná štartovacia kultúra a SCOBY.',
      },
    ],
    createdAt: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kb-active-2',
    userId: 'u1',
    codeNumber: 'KB-043',
    name: 'Zázvorovo-Malinová 2F',
    recipeId: 'rec-moon-mix',
    recipeName: 'Mesačný Mix',
    teaType: 'BLACK_GREEN_MIX',
    volumeLiters: 3.0,
    teaGram: 21,
    sugarGram: 210,
    starterLiquidMl: 300,
    waterLiters: 2.7,
    startDate: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    targetTasteDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    targetBottleDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    state: 'SECOND_FERMENTATION',
    notes: 'Stočené do 6 patentových sklenených fliaš (0.5L). Pridané mrazené maliny a čerstvý zázvor.',
    secondFermentation: {
      id: 'f2-1',
      batchId: 'kb-active-2',
      startDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
      expectedEndDate: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(),
      bottlesCount: 6,
      totalVolumeMl: 3000,
      safetyWarningDismissed: true,
      pressureCheckedDates: [new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString()],
      bottles: [
        {
          id: 'b1',
          volumeMl: 500,
          flavoring: 'Malina & Zázvor',
          fruitGram: 30,
          juiceMl: 10,
          notes: 'Pekná rúžová farba, jemne šumí.',
        },
      ],
    },
    measurements: [],
    history: [
      {
        id: 'h2',
        batchId: 'kb-active-2',
        timestamp: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        previousState: 'FIRST_FERMENTATION',
        newState: 'SECOND_FERMENTATION',
        title: 'Začatá 2. fermentácia',
        description: 'Stočenie do fliaš s malinami a zázvorom. Uložené pri izbovej teplote na perlenie.',
      },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
];
